version: 2.1

orbs:
  node: circleci/node@5.0.2
  android: circleci/android@2.3.0

executors:
  react-native-executor:
    docker:
      - image: cimg/android:2023.09
    working_directory: ~/yourmediaapp

jobs:
  install-dependencies:
    executor: react-native-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-modules-{{ checksum "package-lock.json" }}
      - run:
          name: Install Node dependencies
          command: sudo npm install
      - save_cache:
          paths:
            - node_modules
          key: node-modules-{{ checksum "package-lock.json" }}

  build-android:
    executor: react-native-executor
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Set execute permissions on gradlew
          command: chmod +x android/gradlew
      - run:
          name: Build APK
          command: cd android && ./gradlew assembleDebug

workflows:
  build:
    jobs:
      - install-dependencies
      - build-android:
          requires:
            - install-dependencies
